/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideContainer: typeof import('./components/AsideContainer.vue')['default']
    AssistantMessage: typeof import('./components/AssistantMessage.vue')['default']
    BaseContainer: typeof import('./components/BaseContainer.vue')['default']
    CacheHistoryModal: typeof import('./components/CacheHistoryModal.vue')['default']
    Chat: typeof import('./views/Chat.vue')['default']
    ChatAside: typeof import('./components/ChatAside.vue')['default']
    ChatHeader: typeof import('./components/ChatHeader.vue')['default']
    ChatItem: typeof import('./components/ChatItem.vue')['default']
    ChatLayout: typeof import('./components/ChatLayout.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    ErrorChatMessage: typeof import('./components/ErrorChatMessage.vue')['default']
    ImagePreviewModal: typeof import('./components/ImagePreviewModal.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
    MainContainer: typeof import('./components/MainContainer.vue')['default']
    MessageMetadataBottom: typeof import('./components/MessageMetadataBottom.vue')['default']
    MessageMetadataTop: typeof import('./components/MessageMetadataTop.vue')['default']
    MessageTimer: typeof import('./components/MessageTimer.vue')['default']
    PromptOptimizeButton: typeof import('./components/PromptOptimizeButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectModelModal: typeof import('./components/SelectModelModal.vue')['default']
    SelectPresetModal: typeof import('./components/SelectPresetModal.vue')['default']
    SettingsModal: typeof import('./components/SettingsModal.vue')['default']
    StreamContent: typeof import('./components/StreamContent.vue')['default']
    Translate: typeof import('./views/Translate.vue')['default']
    UserChatMessage: typeof import('./components/UserChatMessage.vue')['default']
    WordExplainPaper: typeof import('./components/WordExplainPaper.vue')['default']
  }
}

// For TSX support
declare global {
  const AsideContainer: typeof import('./components/AsideContainer.vue')['default']
  const AssistantMessage: typeof import('./components/AssistantMessage.vue')['default']
  const BaseContainer: typeof import('./components/BaseContainer.vue')['default']
  const CacheHistoryModal: typeof import('./components/CacheHistoryModal.vue')['default']
  const Chat: typeof import('./views/Chat.vue')['default']
  const ChatAside: typeof import('./components/ChatAside.vue')['default']
  const ChatHeader: typeof import('./components/ChatHeader.vue')['default']
  const ChatItem: typeof import('./components/ChatItem.vue')['default']
  const ChatLayout: typeof import('./components/ChatLayout.vue')['default']
  const ChatMessage: typeof import('./components/ChatMessage.vue')['default']
  const ErrorChatMessage: typeof import('./components/ErrorChatMessage.vue')['default']
  const ImagePreviewModal: typeof import('./components/ImagePreviewModal.vue')['default']
  const ImageUpload: typeof import('./components/ImageUpload.vue')['default']
  const MainContainer: typeof import('./components/MainContainer.vue')['default']
  const MessageMetadataBottom: typeof import('./components/MessageMetadataBottom.vue')['default']
  const MessageMetadataTop: typeof import('./components/MessageMetadataTop.vue')['default']
  const MessageTimer: typeof import('./components/MessageTimer.vue')['default']
  const PromptOptimizeButton: typeof import('./components/PromptOptimizeButton.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SelectModelModal: typeof import('./components/SelectModelModal.vue')['default']
  const SelectPresetModal: typeof import('./components/SelectPresetModal.vue')['default']
  const SettingsModal: typeof import('./components/SettingsModal.vue')['default']
  const StreamContent: typeof import('./components/StreamContent.vue')['default']
  const Translate: typeof import('./views/Translate.vue')['default']
  const UserChatMessage: typeof import('./components/UserChatMessage.vue')['default']
  const WordExplainPaper: typeof import('./components/WordExplainPaper.vue')['default']
}