/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideContainer: typeof import('./components/AsideContainer.vue')['default']
    AssistantChatMessage: typeof import('./components/AssistantChatMessage.vue')['default']
    AssistantMessage: typeof import('./components/AssistantMessage.vue')['default']
    BaseContainer: typeof import('./components/BaseContainer.vue')['default']
    CacheHistoryModal: typeof import('./components/CacheHistoryModal.vue')['default']
    Chat: typeof import('./views/Chat.vue')['default']
    ChatAside: typeof import('./components/ChatAside.vue')['default']
    ChatHeader: typeof import('./components/ChatHeader.vue')['default']
    ChatInput: typeof import('./components/ChatInput.vue')['default']
    ChatItem: typeof import('./components/ChatItem.vue')['default']
    ChatLayout: typeof import('./components/ChatLayout.vue')['default']
    ChatLayoutNew: typeof import('./components/ChatLayoutNew.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    ErrorChatMessage: typeof import('./components/ErrorChatMessage.vue')['default']
    ImagePreviewModal: typeof import('./components/ImagePreviewModal.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
    MainContainer: typeof import('./components/MainContainer.vue')['default']
    MessageMetadata: typeof import('./components/MessageMetadata.vue')['default']
    MessageMetadataBottom: typeof import('./components/MessageMetadataBottom.vue')['default']
    MessageMetadataTop: typeof import('./components/MessageMetadataTop.vue')['default']
    MessageTimer: typeof import('./components/MessageTimer.vue')['default']
    PromptOptimizeButton: typeof import('./components/PromptOptimizeButton.vue')['default']
    RecentChatWrapper: typeof import('./components/RecentChatWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectModelModal: typeof import('./components/SelectModelModal.vue')['default']
    SelectPresetModal: typeof import('./components/SelectPresetModal.vue')['default']
    SettingsModal: typeof import('./components/SettingsModal.vue')['default']
    StreamContent: typeof import('./components/StreamContent.vue')['default']
    StreamingText: typeof import('./components/StreamingText.vue')['default']
    Translate: typeof import('./views/Translate.vue')['default']
    UserChatMessage: typeof import('./components/UserChatMessage.vue')['default']
    WordExplainPaper: typeof import('./components/WordExplainPaper.vue')['default']
  }
}
